# /etc/chatservice/application.yml
spring:
  application:
    name: chatservice
  data:
    mongodb:
      uri: ${MONGODB_URI}
  websocket:
    allowed-origins: "*"

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
